### ISSUE TITLE
Static aggregation team

### ISSUE THREAD

**Issue by pwalsh** [openspending/next#2]
Register your interest in working on the static aggregation team here. See the [Roadmap](http://labs.openspending.org/next/roadmap.html) for more information.

**Comment by pwalsh** [comment]
I'm in.

**Comment by rgrp** [comment]
I'm in.

**Comment by aivuk** [comment]
In.

**Comment by pudo** [comment]
Hey guys, just a heads-up: I've started hacking on a more lightweight replacement for Cubes, called [babbage](https://github.com/pudo/babbage).

While I enjoyed using Cubes, it is designed with a set of constraints that limit it's useful a bit for me. Specifically, operations must be portable across database backends (such as Mixpanel and MongoDB), and all filters must be pre-computable. This means there is no text search, or filtering by other, more complex criteria. There's also still a lot of impedance between my app (SpenDB) and Cubes because their expected metadata is much more complex than what I'm keen to make users generate. 

Why am I posting this? Since babbage is pretty much the same code as cubepress (only a bit more mature), it'd be cool to see if it could supersede that. Let me know.

**Comment by pwalsh** [comment]
Hey @pudo thanks for the heads up. I saw babbage: I was a bit surprised you were rolling your own instead of Cubes. I'll definitely check it out for the static aggregation.

**Comment by pudo** [comment]
Yeah, still not totally sure I want to go down that path. I've been looking at what the PRs for Cubes would look like to do stuff like ``LIKE`` matches, and it just seems like it would completely mess up their design.

**Comment by pwalsh** [comment]
Do you (we) really need text search in a slice & dice backend? Conceptually, I get you on the pre-computable filters, but for the search, not so sure (shouldn't free text search be a set of distinctive endpoints? What is a use case this solves?)

**Comment by pudo** [comment]
Hm. My use case for this is mostly procurement & payment-level data. "Find all the items where the vendor name includes ``Acme Corp`` and aggregate by month" is a reasonable query given the data quality we have to deal with in most cases (e.g. TED, IATI). This isn't quite free-text search (i.e. across-field) which I'm not totally sure needs to be mixed in with aggregation, either. 

The alternative is probably full data-cleaning before querying. The right way, but damn would that be awkward. What do you think?

**Comment by pwalsh** [comment]
Oh right, got it. That's a tough one (in a classical OLAP sense, as Cubes implements). 

Still not sure actually that it should be the same API: this is just a standard type of SQL query, with all the benefits of that, but also the inefficiencies compared to views over data in pre-computed fact tables.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.
